project:
  type: website
  output-dir: docs


website:
  title: "Home"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/yasin27mohammad
      - icon: linkedin
        href: https://www.linkedin.com/in/mohammad-yasin-098787232/?trk=eml-email_pymk_02-header-0-profile_glimmer

format:
  html:
    theme: darkly
    css: styles.css

